### ISSUE TITLE
Season 3 Support Checklist

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Dungeons#150]
NOTE: "final pass on live" checks technically will be done post launch deadline, but every other checkmark should be done by Nov 14th.

Season 3 Dungeon Updates

**Dawn of the Infinite 10.2**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Darkheart Thicket**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Black Rook Hold**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Waycrest Manor**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Atal'Dazar**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Everbloom**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Throne of the Tides**
  - [x] Dungeon Boss mods updated with drycoded new/changed warnings/timers/features for M+
  - [x] Dungeon boss mod drycodes tested and mods completed from real data
  - [x] Dungeon boss additional pass with mythic+ transcriptor log from that testing to refine them further
  - [x] Dungeon Trash mod updated with drycoded warnings for all notable trash as outlined by updated Guides
  - [x] Dungeon Trash mod tested thoroughly on Mythic+ and nameplate timers added
  - [x] Dungeon final pass on live, especially Mythic+

**Comment by MysticalOS** [comment]
Mythic+ Oct 3 Update
  - [ ] Throne of the Tides now has updated encounters and enemies throughout the dungeon
  - [ ] Adjustments to the duration of several story scenes in Dawn of the Infinite on Mythic+ difficulty. (IE new RP timers)
  - [ ] The Yalnu encounter in The Everbloom has been updated.

**Comment by MysticalOS** [comment]
All 10.2 dungeons heavily reviewed and all bosses and trash mods massively updated for all changes and latest DBM features

Barring any changes since ptr of course.

**Comment by MysticalOS** [comment]
Really only thing left are the Dawn of infinite RP timers
